version: '3.8'

services:
   db:
      image: mysql:5.7
      container_name: mysql
      volumes:
        - /j/Desarrollo/github/MyLaziness/docker/mysql/volume:/var/lib/mysql
        # this path is to locate the exportat schemas that you may want to import on your mysql
        - /j/Desarrollo/github/MyLaziness/docker/mysql/Exported_Schemas/:/home 
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: sudo_mlv
        MYSQL_DATABASE: mikes_schema
        MYSQL_USER: mike
        MYSQL_PASSWORD: mlv
      deploy:
        resources:
          limits:
            memory: 700M
          reservations:
            memory: 400M
